= Almacenamiento en caché de volumen de BlueXP
:allow-uri-read: 




=== Almacenamiento en caché de volumen de BlueXP

BlueXP Volume Caching, una característica del software ONTAP 9, es una capacidad de almacenamiento en caché remoto que simplifica la distribución de archivos, reduce la latencia de la WAN al acercar los recursos a donde se encuentran los usuarios y los recursos computacionales, y reduce los costos de ancho de banda de la WAN. El almacenamiento en caché de volumen proporciona un volumen persistente y escribible en un lugar remoto. Puede utilizar BlueXP Volume Caching para acelerar el acceso a los datos o para descargar el tráfico de volúmenes con mucho acceso. Los volúmenes de caché son ideales para cargas de trabajo de lectura intensiva, especialmente cuando los clientes necesitan acceder a los mismos datos repetidamente.

Con BlueXP Volume Caching, tiene capacidades de almacenamiento en caché para la nube, específicamente para Amazon FSx for NetApp ONTAP, Cloud Volumes ONTAP y entornos de trabajo locales.

link:https://docs.netapp.com/us-en/bluexp-volume-caching/get-started/cache-intro.html["Obtenga más información sobre el almacenamiento en caché de volumen"] .
