---
sidebar: sidebar 
permalink: get-started/cache-prerequisites.html 
keywords: what are Volume Caching requirements, Volume Caching prerequisites 
summary: Comience a utilizar el almacenamiento en caché de volumen verificando la compatibilidad con su entorno, acceso a la red, inicio de sesión y navegador web. 
---
= Requisitos previos del almacenamiento en caché de volumen
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Comience verificando la preparación de su entorno operativo, inicio de sesión, acceso a la red y navegador web.

Para utilizar el almacenamiento en caché de volumen, debe asegurarse de que su entorno cumpla con todos los requisitos.

* ONTAP 9.8 y posteriores
+
** Permisos de ONTAP del administrador del clúster
** LIF entre clústeres en los clústeres


* En la NetApp Console:
+
** El agente de la consola debe configurarse en la NetApp Console. Todos los clústeres de origen y destino deben estar en el mismo agente de la consola. Consulta lalink:https://docs.netapp.com/us-en/console-setup-admin/task-quick-start-standard-mode.html["Flujo de trabajo para empezar con NetApp Console"^] y la link:https://docs.netapp.com/us-en/console-setup-admin/concept-agents.html["Obtenga más información sobre los agentes de consola"^].
** Se debe establecer el ambiente de trabajo.
** Los clústeres deben agregarse en el entorno de trabajo de destino y en un estado encendido o degradado.
** Requisitos estándar de la NetApp Console . Referirse a https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-checklist-cm.html["Requisitos de la NetApp Console"^] .



