---
sidebar: sidebar 
permalink: get-started/cache-prerequisites.html 
keywords: what are volume caching requirements, volume caching prerequisites 
summary: Comience a utilizar el almacenamiento en caché de volumen verificando la compatibilidad con su entorno, acceso a la red, inicio de sesión y navegador web. 
---
= Requisitos previos del almacenamiento en caché de volumen
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Comience verificando la preparación de su entorno operativo, inicio de sesión, acceso a la red y navegador web.

Para utilizar el almacenamiento en caché de volumen, debe asegurarse de que su entorno cumpla con todos los requisitos.

* ONTAP 9.8 y posteriores
+
** Permisos de ONTAP del administrador del clúster
** LIF entre clústeres en los clústeres


* En la consola de NetApp :
+
** El agente de consola debe configurarse en la consola de NetApp .  Todos los clústeres de origen y destino deben estar en el mismo agente de consola. Consulte la https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-quick-start-standard-mode.html["Inicio rápido de BlueXP"^] y https://docs.netapp.com/us-en/bluexp-setup-admin/concept-connectors.html["Obtenga más información sobre los agentes de consola"^] .
** Se debe preparar el ambiente de trabajo.
** Los clústeres deben agregarse en el entorno de trabajo de destino y en un estado encendido o degradado.
** Requisitos estándar de la consola NetApp . Referirse a https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-checklist-cm.html["Requisitos de la consola de NetApp"^] .



