---
sidebar: sidebar 
permalink: release-notes/cache-whats-new.html 
keywords: Volume Caching faq, bluexp, Volume Caching frequently asked questions 
summary: El almacenamiento en caché de volumen proporciona un volumen persistente y escribible en un lugar remoto. Puede utilizar el almacenamiento en caché de volumen para acelerar el acceso a los datos o para descargar el tráfico de volúmenes con mucho acceso. Los volúmenes de caché son ideales para cargas de trabajo de lectura intensiva, especialmente cuando los clientes necesitan acceder a los mismos datos repetidamente. 
---
= Novedades en el almacenamiento en caché de volumen
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Descubra las novedades en el almacenamiento en caché de volumen.



[[06-october-2025]]
== 6 de octubre de 2025



[[bluexp-volume-caching-is-now-volume-caching]]
=== El almacenamiento en caché de volumen de BlueXP ahora es almacenamiento en caché de volumen

El almacenamiento en caché de volumen de BlueXP ha cambiado de nombre a Almacenamiento en caché de volumen.

Puede acceder a él desde la barra de navegación izquierda de la NetApp Console seleccionando *Movilidad* > *Almacenamiento en caché de volumen*.



[[bluexp-is-now-netapp-console]]
=== BlueXP ahora es NetApp Console

La NetApp Console, construida sobre la base BlueXP mejorada y reestructurada, proporciona una gestión centralizada del almacenamiento de NetApp y de los NetApp Data Services en entornos locales y en la nube a nivel empresarial, brindando información en tiempo real, flujos de trabajo más rápidos y una administración simplificada, que es altamente segura y compatible.

Para obtener más detalles sobre lo que ha cambiado, consulte lalink:https://docs.netapp.com/us-en/bluexp-relnotes/index.html["Notas de la versión de la NetApp Console"] .



[[04-june-2023]]
== 4 de junio de 2023



[[bluexp-volume-caching]]
=== Almacenamiento en caché de volumen de BlueXP

BlueXP Volume Caching, una característica del software ONTAP 9, es una capacidad de almacenamiento en caché remoto que simplifica la distribución de archivos, reduce la latencia de la WAN al acercar los recursos a donde se encuentran los usuarios y los recursos computacionales, y reduce los costos de ancho de banda de la WAN. El almacenamiento en caché de volumen proporciona un volumen persistente y escribible en un lugar remoto. Puede utilizar BlueXP Volume Caching para acelerar el acceso a los datos o para descargar el tráfico de volúmenes con mucho acceso. Los volúmenes de caché son ideales para cargas de trabajo de lectura intensiva, especialmente cuando los clientes necesitan acceder a los mismos datos repetidamente.

Con BlueXP Volume Caching, tiene capacidades de almacenamiento en caché para la nube, específicamente para Amazon FSx for NetApp ONTAP, Cloud Volumes ONTAP y entornos de trabajo locales.

link:https://docs.netapp.com/us-en/bluexp-volume-caching/get-started/cache-intro.html["Obtenga más información sobre el almacenamiento en caché de volumen"] .
