---
sidebar: sidebar 
permalink: release-notes/cache-whats-new.html 
keywords: volume caching faq, bluexp, volume caching frequently asked questions 
summary: El almacenamiento en caché de volumen proporciona un volumen persistente y escribible en un lugar remoto.  Puede utilizar el almacenamiento en caché de volumen para acelerar el acceso a los datos o para descargar el tráfico de volúmenes con mucho acceso.  Los volúmenes de caché son ideales para cargas de trabajo de lectura intensiva, especialmente cuando los clientes necesitan acceder a los mismos datos repetidamente. 
---
= Novedades en el almacenamiento en caché de volumen
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Descubra las novedades en el almacenamiento en caché de volumen.



== 6 de octubre de 2025



=== El BlueXP volume caching ahora es almacenamiento en caché de volumen

El BlueXP volume caching ha cambiado de nombre a almacenamiento en caché de volumen.

Puede acceder a él desde la barra de navegación izquierda de la consola NetApp seleccionando *Movilidad* > *Almacenamiento en caché de volumen*.



=== BlueXP ahora es NetApp Console

La consola NetApp , construida sobre la base BlueXP mejorada y reestructurada, proporciona una gestión centralizada del almacenamiento NetApp y de los servicios de datos NetApp en entornos locales y en la nube a nivel empresarial, brindando información en tiempo real, flujos de trabajo más rápidos y una administración simplificada, que es altamente segura y compatible.

Para obtener más detalles sobre lo que ha cambiado, consulte lalink:https://docs.netapp.com/us-en/bluexp-relnotes/index.html["Notas de la versión de la consola de NetApp"] .



== 4 de junio de 2023



=== BlueXP volume caching

El BlueXP volume caching, una característica del software ONTAP 9, es una capacidad de almacenamiento en caché remoto que simplifica la distribución de archivos, reduce la latencia de la WAN al acercar los recursos a donde se encuentran los usuarios y los recursos computacionales, y reduce los costos de ancho de banda de la WAN.  El almacenamiento en caché de volumen proporciona un volumen persistente y escribible en un lugar remoto.  Puede utilizar el BlueXP volume caching para acelerar el acceso a los datos o para descargar el tráfico de volúmenes con mucho acceso.  Los volúmenes de caché son ideales para cargas de trabajo de lectura intensiva, especialmente cuando los clientes necesitan acceder a los mismos datos repetidamente.

Con el BlueXP volume caching, tiene capacidades de almacenamiento en caché para la nube, específicamente para Amazon FSx for NetApp ONTAP, Cloud Volumes ONTAP y entornos de trabajo locales.

link:https://docs.netapp.com/us-en/bluexp-volume-caching/get-started/cache-intro.html["Obtenga más información sobre el almacenamiento en caché de volumen"] .
